name: CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.x

      - run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo VITE_API_URL=${{ secrets.DEV_VITE_API_URL }} >> .env
          echo VITE_HMAC_SECRET_KEY=${{ secrets.VITE_HMAC_SECRET_KEY }} >> .env
          cat .env

      - run: npm run build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - run: aws s3 sync ./dist s3://dev.sos-rs.com
